### ISSUE TITLE
Unable to instantiate module 'AWSCore': aws-c-common.lib not found

### ISSUE THREAD

**Issue by Jeff-Stapleton** [chris-gong/gamelift-example-ue4#1]
I am trying to build your example project. I copied the server and the client .dlls and .libs into their respective plugin folders. However when I attempt to build the project the error:

`UnrealBuildTool : error : Unable to instantiate module 'AWSCore': aws-c-common.lib not found. Expected in this location: C:\Users\jeffd\Documents\GitHub\gamelift-example-ue4\Plugins\GameLiftClientSDK\ThirdParty\GameLiftClientSDK\Win64\aws-c-common.lib
1>                        (referenced via GameLiftTutorial.uproject -> GameLiftClientSDK.uplugin)
1>                        (see ../Programs/UnrealBuildTool/Log.txt for full exception trace)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: The command "D:\Games\Epic\UE_4.21\Engine\Build\BatchFiles\Rebuild.bat GameLiftTutorialEditor Win64 Development "C:\Users\jeffd\Documents\GitHub\gamelift-example-ue4\GameLiftTutorial.uproject" -WaitMutex -FromMsBuild" exited with code -1.
1>Done building project "GameLiftTutorial.vcxproj" -- FAILED.`

is thrown. I am not sure where I am suppose to obtain this .lib 
I think you meant to link to a source to obtain all .dll and .lib files needed but they are missing from the readme. I used the link that was provided in your youtube video but that source seems to be missing the above mentioned .lib

**Comment by chris-gong** [comment]
Closing this issue since we have moved on from the gamelift client sdk to using http requests, lambda functions and api gateway instead.
