### ISSUE TITLE
Try to remake Google sign-in

### ISSUE THREAD

**Issue by 0xsmft** [chris-gong/gamelift-example-ue4#9]
Try to remake Google sign-in that's it really

**Comment by chris-gong** [comment]
I've thought of this, but not entirely sure if I want to do this because it's a lot of work.

**Comment by 0xsmft** [comment]
yeah

**Comment by chris-gong** [comment]
Closing this issue to keep new ideas consolidated in this issue, https://github.com/chris-gong/gamelift-example-ue4/issues/8

**Comment by 0xsmft** [comment]
Okay.
